version: "3.9"
services:
  db:
    container_name: db_container
    image: postgres:13.3
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - postgres
  
  market_tgbot:
    build: .
    container_name: tgbot
    command: python -m tgbot
    volumes:
      - .:/tg_app
    working_dir: /tg_app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 600M
        reservations:
          memory: 256M
    networks:
      - postgres


networks:
  postgres:
    driver: bridge